# Generated by Django 3.2 on 2022-12-18 17:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
