# Generated by Django 3.2 on 2022-12-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_recomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='recomment',
            options={'verbose_name_plural': 'Recomments'},
        ),
    ]
