# Generated by Django 3.2 on 2022-12-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221218_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
